"""empty message

Revision ID: 081f9d7d59e9
Revises: 6514b4bc765f
Create Date: 2024-07-18 10:32:28.162123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081f9d7d59e9'
down_revision = '6514b4bc765f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_inscription', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_inscription')

    # ### end Alembic commands ###
